{{- if .Values.clamav.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mnemoshare.fullname" . }}-clamav
  labels:
    {{- include "mnemoshare.labels" . | nindent 4 }}
    app.kubernetes.io/component: clamav
spec:
  type: ClusterIP
  ports:
    - port: 1344
      targetPort: icap
      protocol: TCP
      name: icap
  selector:
    {{- include "mnemoshare.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: clamav
{{- end }}
