{{- if and .Values.redis.enabled .Values.redis.password (not .Values.redis.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mnemoshare.fullname" . }}-redis
  labels:
    {{- include "mnemoshare.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
type: Opaque
data:
  redis-password: {{ .Values.redis.password | b64enc | quote }}
{{- end }}
