apiVersion: v1
kind: Service
metadata:
  name: {{ include "mnemoshare.fullname" . }}
  labels:
    {{- include "mnemoshare.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.mtls.enabled }}
    - port: {{ .Values.mtls.port | default 8443 }}
      targetPort: mtls
      protocol: TCP
      name: mtls
    {{- end }}
  selector:
    {{- include "mnemoshare.selectorLabels" . | nindent 4 }}
